# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.

name: context-transient
on: [push, pull_request]

jobs:
  melpazoid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: yezz123/setup-uv@v4
    - run: uv --version
    - name: Install
      run: |       
        sudo apt-get install emacs && emacs --version
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        uv pip install --system --no-cache-dir ~/melpazoid
    - name: Run
      env:
        LOCAL_REPO: ${{ github.workspace }}
        # RECIPE is your recipe as written for MELPA:
        RECIPE: (context-transient :repo "licht1stein/context-transient" :fetcher github)
        # set this to false (or remove it) if the package isn't on MELPA:
        EXIST_OK: true
      run: echo $GITHUB_REF && make -C ~/melpazoid
